# Generated by Django 3.2.8 on 2021-10-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='img_name')),
                ('date', models.DateField(verbose_name='date')),
                ('explanation', models.TextField(verbose_name='explanation')),
                ('url', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
